name: Conflict PR Test

on:
  push:
    branches:
      - main

jobs:
  test-conflict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for conflicts
        run: |
          echo "Conflicts: ${{ steps.rebase.outputs.conflicts }}"

      - name: Create PR for conflicts
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: conflicts to resolve"
          title: "chore: conflicts to resolve"
          body: "This PR contains merge conflicts that need manual resolution."
          branch: fix/conflict-update-dev-with-main
          base: dev
          branch-suffix: short-commit-hash
          delete-branch: false
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"