name: Tag & Release on PR merge to main

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

permissions:
  contents: write

jobs:
  tag_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Decide bump (hotfix/* => patch, dev => minor)
        id: decide
        run: |
          SRC=${{ github.event.pull_request.head.ref }}
          # Safely read PR title using here-doc to prevent shell interpretation of backticks
          IFS= read -r PR_TITLE <<'GITHUB_ACTIONS_EOF'
          ${{ toJson(github.event.pull_request.title) }}
          GITHUB_ACTIONS_EOF
          # Remove surrounding JSON quotes and unescape JSON escape sequences
          PR_TITLE="${PR_TITLE#\"}"
          PR_TITLE="${PR_TITLE%\"}"
          PR_TITLE="${PR_TITLE//\\\"/\"}"
          PR_TITLE="${PR_TITLE//\\\\/\\}"
          PR_TITLE="${PR_TITLE//\\`/`}"
          PR_LABELS=${{ github.event.pull_request.labels }}
          LABEL=${{ toJson(github.event.pull_request.labels) }}
          echo $LABEL
         
          # Check if the title or labels contain "major"
          if [[ "$PR_TITLE" == *"MAJOR Release"* ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif [[ "$SRC" == hotfix/* ]]; then
            echo "bump=patch" >> $GITHUB_OUTPUT
          elif [[ "$SRC" == "dev" ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT 
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: ${{ steps.decide.outputs.bump }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
